# Generated by Django 6.0.7 on 2026-07-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedTickerPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("ticker", models.CharField(max_length=8, unique=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
