# Generated by Django 6.0.7 on 2026-07-27 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulations", "0002_portfolio_study_and_holding_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyViews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("asset", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "x_axis",
                    models.CharField(
                        choices=[("time", "Time")], default="time", max_length=16
                    ),
                ),
                (
                    "y_axis",
                    models.CharField(
                        choices=[("value", "Value"), ("cagr", "CAGR")],
                        default="value",
                        max_length=16,
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="simulations.study",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
