# Generated by Django 6.0.7 on 2026-07-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulations", "0003_studyviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studyviews",
            name="y_axis",
            field=models.CharField(
                choices=[
                    ("value", "Value"),
                    ("profit_loss", "Profit/Loss"),
                    ("cagr", "CAGR"),
                ],
                default="value",
                max_length=16,
            ),
        ),
    ]
